name: Semantic Versioning

on:
  push:
    branches:
      - master
      - staging
      - develop
  workflow_dispatch:


jobs:
  generate_new_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Genarate New Version
        id: generate_new_version
        uses: paulhatch/semantic-version@v5.3.0
      - name: Create And Push New Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.generate_new_version.outputs.version_tag }}_${{ github.ref_name }}
          git push origin ${{ steps.generate_new_version.outputs.version_tag }}_${{ github.ref_name }}
